include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # 项目早期，部分 lint 提示而非阻塞
    avoid_print: warning
    unawaited_futures: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unawaited_futures: false
